### PR TITLE
fix: fixes conflict-related issues

### LINKED ISSUE #18: [Rollback] Conflict-related issues
Here are 3 distinct use cases where rollbacking will not work and throw `Updating the path 'X' would create a conflict at 'Y'`.

## Rollbacking a specific array element

Initial document
```ts
{
  array: ['a', 'b']
}
```

Migration query:
```ts
{ 
  $set: { 
    'array.1': 'new b' 
  } 
}
```

Generated rollback query:
```json
{
  "$set": {
    "_id": "6720f5a6efc5558c18b3a795",
    "array": [
      "a",
      "b"
    ]
  },
  "$unset": {
    "array.1": 1
  }
}
```

`Updating the path 'array.1' would create a conflict at 'array'`

## Rollbacking a specific array element (nested)

Initial document
```ts
{
  array: [
    null,
    {
      nestedArray: [null, 'b']
    },
  ],
};
```

Migration query:
```ts
{ 
  $set: { 
    'array.1.nestedArray.1': 'new b'
  } 
}
```

Generated rollback query:
```json
{
  "$set": {
    "_id": "6720f5daf91fae9d26b6990f",
    "array": [
      null
    ],
    "array.1.nestedArray": [
      null,
      "b"
    ]
  },
  "$unset": {
    "array.1.nestedArray.1": 1
  }
}
```

`Updating the path 'array.1.nestedArray' would create a conflict at 'array'`

## Rollbacking a number-indexed object

Initial document
```ts
{
  object: {
    0: 'a',
    1: 'b'
  },
};
```

Migration query:
```ts
{ 
  $set: { 
    'object.1': 'new b'
  } 
}
```

Generated rollback query:
```json
{
  "$set": {
    "_id": "6720f61a1f16e5169e89423e",
    "object": "b"
  },
  "$unset": {
    "object.1": 1
  }
}
```

`Updating the path 'object.1' would create a conflict at 'object'`

### PR DESCRIPTION
**Pull request by hugop95**
Fixes #18

Each commit fixes one issue.

- Commit 1: Rollbacking a specific array element.
- Commit 2: Rollbacking a specific array element (nested).
- Commit 3: Rollbacking a number-indexed object.

### Rollbacking a specific array element

Initial document
```ts
{
  array: ['a', 'b']
}
```

Migration query:
```ts
{ 
  $set: { 
    'array.1': 'new b' 
  } 
}
```

Generated rollback query:
```json
{
  "$set": {
    "_id": "6720f5a6efc5558c18b3a795",
    "array": [
      "a",
      "b"
    ]
  },
  "$unset": {
    "array.1": 1
  }
}
```

### Proposed fix

For a field `X` to be added to the `$unset` section, there must not be any key `K` from the `$set` section where `${K}.` is included in `X` (`array.1` must not include `array.` in the example above).

### Rollbacking a specific array element (nested)

Initial document
```ts
{
  array: [
    null,
    {
      nestedArray: [null, 'b']
    },
  ],
};
```

Migration query:
```ts
{ 
  $set: { 
    'array.1.nestedArray.1': 'new b'
  } 
}
```

Generated rollback query:
```json
{
  "$set": {
    "_id": "6720f5daf91fae9d26b6990f",
    "array": [
      null
    ],
    "array.1.nestedArray": [
      null,
      "b"
    ]
  },
  "$unset": {
    "array.1.nestedArray.1": 1
  }
}
```

The issue comes from the fact that we always set the complete array when we should be updating specific elements sometimes.

It's better in terms of performance to set an array completely rather than individually set its elements, so let's ensure that this remains the standard behavior when possible.

### Proposed fix

After flattening the backup document, while iterating on its keys/values, the idea is to add an additional check when we encounter an array to restore: check if among the properties set during the update, a "deeper" key exists.

If that's the case, we should use
`rollbackSet[${nestedPathToArray}.${index}] = value;`
rather than
`rollbackSet[nestedPathToArray][Number(index)] = value;`

### Rollbacking a number-indexed object

Initial document
```ts
{
  object: {
    0: 'a',
    1: 'b'
  },
};
```

Migration query:
```ts
{ 
  $set: { 
    'object.1': 'new b'
  } 
}
```

Generated rollback query:
```json
{
  "$set": {
    "_id": "6720f61a1f16e5169e89423e",
    "object": "b"
  },
  "$unset": {
    "object.1": 1
  }
}
```

Individual array element setting have the same syntax as this case.

### Fix proposed

Replace `rollbackSet[nestedPathToArray] = value;` with `rollbackSet[key] = value;`.

The `rollbackSet[nestedPathToArray] = value;` line was not covered by tests so I think unexpected side effects on that change are minimal.

## Checklist

- [x] Test new version on dev (locally).
- [x] Test new version on staging (locally).

### CODE REVIEW

**Comment by hugop95** [comment]
Hi @LucVidal360 @pp0rtal 👋

As @pp0rtal mentioned, I think it would be a good idea to create a RC and test this version in the CI if possible. I have tested it locally and things work as expected, but an additional check would be welcomed.

**Review by LucVidal360 — APPROVED** [review]
@hugop95 Thank you for all this work. I guess you had fun :grin:

**Comment by hugop95** [comment]
@LucVidal360 It sure was! 😁

**Review by pp0rtal — APPROVED** [review]
> The issue comes from the fact that we always set the complete array when we should be updating specific elements sometimes.

Indeed we are usually overwriting everything which is simplifying a lot. Auto-rollback is magic but has limit (when we $pull a value for instance...)
But here no doubt: your changes make perfectly sense, and are idempotent :ok_hand: 

> The `rollbackSet[nestedPathToArray] = value;` line was not covered by tests so I think unexpected side effects on that change are minimal.

Right move :+1: 
In any case they will occur in the next minor (not patch) release.

**Comment by pp0rtal** [comment]
@hugop95 Thanks **a lot** for this contribution! :rocket:

**Pull request merged**
